[[actions]]
name = "play"
platform = "windows"
path = "Lifegen/ScavGen.exe"
args = ["--launched-through-itch"]

[[actions]]
name = "play"
platform = "linux"
path = "Lifegen/ScavGen"
args = ["--launched-through-itch"]